hub:
    cookieSecret: ""
    image:
        name: jackmoore/hub
        tag: cc2714c254f33f97f60386df0fbff291
proxy:
    secretToken: ""
singleuser:
    extraEnv:
        ENGINE_ADDRESS: "https://[MASTER_IP]:30001"
    storage:
        type: dynamic
        static:
            pvcName: null
            subPath: "{username}"
        capacity: 10Gi
        homeMountPath: /home/jovyan/work
    image:
        name: jackmoore/notebook
        tag: cc2714c254f33f97f60386df0fbff291
    lifecycleHooks:
        postStart:
            exec:
                command: ["/bin/sh","-c","bash /$HOME/post_start.sh > /$HOME/post_start_out.txt"]
        preStop:
            exec:
                command: ["/bin/sh","-c","bash /$HOME/pre_stop.sh > /$HOME/output.txt"]
auth:
    type: github
    github:
        clientId: ""
        clientSecret: ""
        callbackUrl: "http://[MASTER_IP]/hub/oauth_callback"
cull:
    enabled: true
    timeout: 3600
    every: 600
