apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: connect
  name: connect
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    service: connect
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: connect
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: connect
    spec:
      containers:
      - image: fastscore/connect:latest
        name: connect
        ports:
        - containerPort: 8001
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: dashboard
  name: dashboard
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  selector:
    service: dashboard
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dashboard
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: dashboard
    spec:
      containers:
      - env:
        - name: CONNECT_PREFIX
          value: "https://connect:8001"
        image: fastscore/dashboard:latest
        name: dashboard
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: model-manage
  name: model-manage
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    service: model-manage
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: model-manage
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: model-manage
    spec:
      containers:
      - env:
        - name: CONNECT_PREFIX
          value: "https://connect:8001"
        image: fastscore/model-manage:latest
        name: model-manage
        ports:
        - containerPort: 8002
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: database
  name: database
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    service: database
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: database
    spec:
      containers:
      - image: fastscore/model-manage-mysql:latest
        name: database
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
