apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: NodePort
  selector:
    app: Kafka
  ports:
    - port: 31092
      targetPort: 31092
      nodePort: 31092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-deploy
spec:
  template:
    metadata:
      labels:
        app: Kafka
    spec:
      containers:
      - image: wurstmeister/kafka
        name: kafka
        env:
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:31092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-svc:31092
        - name: KAFKA_CREATE_TOPICS
          value: "notify:1:1,input:1:1,output:1:1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zook:2181
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "5000000"
        ports:
        - containerPort: 31092
---
apiVersion: v1
kind: Service
metadata:
  name: zook
spec:
  type: NodePort
  selector:
    app: zook
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 32181
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zook
spec:
  template:
    metadata:
      labels:
        app: zook
    spec:
      containers:
      - image: wurstmeister/zookeeper
        name: zookeeper
        ports:
        - containerPort: 2181
